# Generated by Django 6.1.1 on 2026-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='mal_id',
            field=models.TextField(unique=True),
        ),
    ]
