# Generated by Django 6.1.1 on 2026-10-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
