# Generated by Django 6.1.1 on 2026-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_alter_backlogitem_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='current_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
