# Generated by Django 6.1.1 on 2026-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosopher_id', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('title_of_work', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('unique_words', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
            ],
        ),
    ]
