# Generated by Django 6.1.1 on 2026-10-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Philosopher',
            fields=[
                ('philosopher_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('quote_id', models.UUIDField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('title_of_work', models.CharField(max_length=255)),
                ('unique_words', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('philosopher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='philosophy.philosopher')),
            ],
        ),
    ]
