# Generated by Django 6.1.1 on 2026-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_id', models.UUIDField(unique=True)),
                ('title', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('current_chapter', models.CharField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField()),
            ],
        ),
    ]
