# Generated by Django 6.1.1 on 2026-10-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('mal_id', models.TextField()),
                ('media_type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga')], max_length=50)),
                ('current_progress', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
