# Generated by Django 6.1.2 on 2026-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('mal_id', models.IntegerField(unique=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga')], max_length=5)),
                ('catalog_type', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('episodes_volumes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
