# Generated by Django 6.1.2 on 2026-10-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='episodes_volumes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
